source 'https://rubygems.org'
gem 'activesupport', '>= 3'
gem 'addressable', '>= 2.3'
gem 'fhir_dstu2_models', '>= 1.1.1'
gem 'fhir_models', '>= 4.2.1'
gem 'fhir_stu3_models', '>= 3.1.1'
gem 'nokogiri', '>= 1.10.4'
gem 'oauth2', '~> 1.1'
gem 'rack', '>= 1.5'
gem 'rest-client', '~> 2.0'
gem 'tilt', '>= 1.1'
gem 'rails', '~> 4.2.0'