name: Check Bundler

on:
  workflow_dispatch:
    inputs:
      bundler_version:
        description: 'Bundler Version'
        required: true
        type: string
      compat_id:
        description: 'Compatibility Id in the format 123'
        required: false
        default: ''
      rails_version:
        description: 'Rails version to use in the format 6.1.0'
        required: true
        default: '6.1.0'
      ruby_version:
        description: 'Ruby Version'
        required: true
        type: string
      dependencies:
        description: 'Dependencies in the format cronex:>=0.13.0,fugit:~>1.8,globalid:>=1.0.1,sidekiq:>=6'
        required: true
        default: 'cronex:>=0.13.0,fugit:~>1.8,globalid:>=1.0.1,sidekiq:>=6'


jobs:
  check_bundler:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ruby 3.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Install dependencies
      run: bundle install

    - name: Run check_bundler script
      run: ./exe/check_bundler.sh --compat_id '${{ github.event.inputs.compat_id }}' --rails_version '${{ github.event.inputs.rails_version }}' --dependencies '${{ github.event.inputs.dependencies }}'